# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lwz_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lwz_model.proto',
  package='lwz_example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0flwz_model.proto\x12\x0blwz_example\"7\n\x0blwz_Request\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x03\"0\n\x0clwz_Response\x12\x11\n\tstu_class\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\x03\x32J\n\x05model\x12\x41\n\x08lwz_show\x12\x18.lwz_example.lwz_Request\x1a\x19.lwz_example.lwz_Response\"\x00\x62\x06proto3')
)




_LWZ_REQUEST = _descriptor.Descriptor(
  name='lwz_Request',
  full_name='lwz_example.lwz_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='lwz_example.lwz_Request.index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='lwz_example.lwz_Request.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='lwz_example.lwz_Request.age', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=87,
)


_LWZ_RESPONSE = _descriptor.Descriptor(
  name='lwz_Response',
  full_name='lwz_example.lwz_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stu_class', full_name='lwz_example.lwz_Response.stu_class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grade', full_name='lwz_example.lwz_Response.grade', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['lwz_Request'] = _LWZ_REQUEST
DESCRIPTOR.message_types_by_name['lwz_Response'] = _LWZ_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

lwz_Request = _reflection.GeneratedProtocolMessageType('lwz_Request', (_message.Message,), {
  'DESCRIPTOR' : _LWZ_REQUEST,
  '__module__' : 'lwz_model_pb2'
  # @@protoc_insertion_point(class_scope:lwz_example.lwz_Request)
  })
_sym_db.RegisterMessage(lwz_Request)

lwz_Response = _reflection.GeneratedProtocolMessageType('lwz_Response', (_message.Message,), {
  'DESCRIPTOR' : _LWZ_RESPONSE,
  '__module__' : 'lwz_model_pb2'
  # @@protoc_insertion_point(class_scope:lwz_example.lwz_Response)
  })
_sym_db.RegisterMessage(lwz_Response)



_MODEL = _descriptor.ServiceDescriptor(
  name='model',
  full_name='lwz_example.model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=139,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='lwz_show',
    full_name='lwz_example.model.lwz_show',
    index=0,
    containing_service=None,
    input_type=_LWZ_REQUEST,
    output_type=_LWZ_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['model'] = _MODEL

# @@protoc_insertion_point(module_scope)
