# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws_push.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ws_push.proto',
  package='ws_push',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rws_push.proto\x12\x07ws_push\"+\n\rWsPushRequest\x12\x0c\n\x04\x61rea\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1d\n\x0bWsPushReply\x12\x0e\n\x06result\x18\x01 \x01(\t2Q\n\rWsPushHandler\x12@\n\x0ePushToWsClient\x12\x16.ws_push.WsPushRequest\x1a\x14.ws_push.WsPushReply\"\x00\x62\x06proto3')
)




_WSPUSHREQUEST = _descriptor.Descriptor(
  name='WsPushRequest',
  full_name='ws_push.WsPushRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='area', full_name='ws_push.WsPushRequest.area', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ws_push.WsPushRequest.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)


_WSPUSHREPLY = _descriptor.Descriptor(
  name='WsPushReply',
  full_name='ws_push.WsPushReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ws_push.WsPushReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['WsPushRequest'] = _WSPUSHREQUEST
DESCRIPTOR.message_types_by_name['WsPushReply'] = _WSPUSHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WsPushRequest = _reflection.GeneratedProtocolMessageType('WsPushRequest', (_message.Message,), {
  'DESCRIPTOR' : _WSPUSHREQUEST,
  '__module__' : 'ws_push_pb2'
  # @@protoc_insertion_point(class_scope:ws_push.WsPushRequest)
  })
_sym_db.RegisterMessage(WsPushRequest)

WsPushReply = _reflection.GeneratedProtocolMessageType('WsPushReply', (_message.Message,), {
  'DESCRIPTOR' : _WSPUSHREPLY,
  '__module__' : 'ws_push_pb2'
  # @@protoc_insertion_point(class_scope:ws_push.WsPushReply)
  })
_sym_db.RegisterMessage(WsPushReply)



_WSPUSHHANDLER = _descriptor.ServiceDescriptor(
  name='WsPushHandler',
  full_name='ws_push.WsPushHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushToWsClient',
    full_name='ws_push.WsPushHandler.PushToWsClient',
    index=0,
    containing_service=None,
    input_type=_WSPUSHREQUEST,
    output_type=_WSPUSHREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WSPUSHHANDLER)

DESCRIPTOR.services_by_name['WsPushHandler'] = _WSPUSHHANDLER

# @@protoc_insertion_point(module_scope)
